steps:
  # Clone Git local
#  - name: gcr.io/cloud-builders/git
#    args: ["fetch", "--unshallow"]

  # Maven compile
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']

  # Create image Docker
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", 
      "-t", "eu.gcr.io/$PROJECT_ID/api-traces-quarkus:jvm", 
      "--file", "src/main/docker/Dockerfile.jvm", 
      "."]

  # Push into Docker Repository
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push", "eu.gcr.io/$PROJECT_ID/api-traces-quarkus:jvm"]

  # Deploy Cloud Run configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta', 'run', 
      'deploy', 'api-traces-quarkus', 
      '--image', "eu.gcr.io/$PROJECT_ID/api-traces-quarkus:jvm",
      '--region', '$_REGION', 
      '--platform', 'managed', 
      '--memory', '128Mi',
#      '--namespace', 'builds',
#      '--cpu', '1',
      '--max-instances', '1',
      '--timeout', '1m',
      '--labels', 'api=traces,impl=quarkus',
#      '--update-env-vars', 'PORT=8085',
      '--allow-unauthenticated'
#      '--service-account', 'client-builds@'
      ]

timeout: 660s
tags: [
  'api-traces-quarkus']
images: [
  "eu.gcr.io/$PROJECT_ID/api-traces-quarkus"]
