apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-traces-quarkus
  labels:
    app: api-traces-quarkus
spec:
  selector:
    matchLabels:
      app: api-traces-quarkus
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-traces-quarkus
    spec:
      containers:
      - name: api-traces-quarkus
        image: enterprise-flows-repository/api-traces-quarkus:jvm
        ports:
        - containerPort: 8083
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 100Mi
        #   limits:
        #     cpu: 400m
        #     memory: 200Mi
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8083
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 30
