apiVersion: v1
kind: Service
metadata:
  name: api-traces-quarkus
  namespace: default
  labels:
    app: api-traces-quarkus
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: api-traces-quarkus
  type: NodePort


